### Get all contacts
GET https://project1-c5z2.onrender.com/contacts

### Create a new contact
POST https://project1-c5z2.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Candy",
  "lastName": "Kinser",
  "email": "candy@example.com",
  "favoriteColor": "beige",
  "birthday": "1955-02-12"
}

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99ccd0bb3731ad6e0fc0e

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99cac0bb3731ad6e0fc0c

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99ccd0bb3731ad6e0fc0e

### Update a Contact
PUT https://project1-c5z2.onrender.com/contacts/68cdc39bcecaad5a963236eb HTTP/1.1
Content-Type: application/json

{
  "firstName": "Leonard",
  "lastName": "Briggs",
  "email": "leo@example.com",
  "favoriteColor": "forest green",
  "birthday": "2016-30-01"
}

### Delete a Contact
DELETE https://project1-c5z2.onrender.com/contacts/68cde6fe8c29a411a848ff96 HTTP/1.1
