### Get all contacts
GET https://project1-c5z2.onrender.com/contacts

### Create a new contact
# POST https://project1-c5z2.onrender.com/contacts
# Content-Type: application/json

# {
#   "firstName": "Ollie",
#   "lastName": "Briggs",
#   "email": "ollie@example.com",
#   "favoriteColor": "blue",
#   "birthday": "2017-06-06"
# }


### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99ccd0bb3731ad6e0fc0e

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99cac0bb3731ad6e0fc0c

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99ccd0bb3731ad6e0fc0e