### Get all contacts
GET https://project1-c5z2.onrender.com/contacts

### Create a new contact
POST https://project1-c5z2.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Lissie",
  "lastName": "Briggs",
  "email": "Lissie@example.com",
  "favoriteColor": "pink",
  "birthday": "2014-03-13"
}

### Update a Contact
PUT https://project1-c5z2.onrender.com/contacts/68cdc5b2cecaad5a963236ec HTTP/1.1
Content-Type: application/json

{
  "firstName": "Lissie",
  "lastName": "Briggs",
  "email": "lissie@example.com",
  "favoriteColor": "red",
  "birthday": "2014-03-13"
}

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99ccd0bb3731ad6e0fc0e

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99cac0bb3731ad6e0fc0c

### Get a single contact
GET https://project1-c5z2.onrender.com/contacts/68c99ccd0bb3731ad6e0fc0e

### Delete a Contact
DELETE https://project1-c5z2.onrender.com/contacts/68cdc175cecaad5a963236ea HTTP/1.1
